name: Deploy Node.js Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Source Code Checkout
        uses: actions/checkout@v3

      - name: NodeJS Install v22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install production dependencies only
        run: npm install --omit=dev

      - name: Zip Lambda function
        run: |
          zip -r function.zip . -x "*.git*" "*.github*" "test/*" "README.md"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy to AWS Lambda (function name is public-website)
        run: |
          aws lambda update-function-code \
            --function-name public-website \
            --zip-file fileb://function.zip
